stages:
  data_collection:
    cmd: python src/data_collection.py
    deps:
    - csv/water_potability.csv
    - src/data_collection.py
    params: 
    - data_collection.test_size
    outs:
    - data/raw
  data_preparation:
    cmd: python src/data_preparation.py
    deps:
    - data/raw
    - src/data_preparation.py
    outs:
    - data/processed
  model_building:
    cmd: python src/model_building.py
    deps:
    - data/processed
    - src/model_building.py
    params:
    - model_building.n_estimators
    outs:
    - model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - model.pkl
    - src/model_evaluation.py
    metrics:
    - metrics.json
